defaults:
  - _self_
  - alg: pwm_48M

general:
  logdir: logs # subfolder to which to log
  device: cuda:0
  run_wandb: False
  seed: 42
  # which world model checkpoint to load
  checkpoint: 
  # offline task data which to load; it sifts through all of tdmpc data chunks
  data_dir: 
  eval_runs: 10 # number of seeds to evaluate
  epochs: 10_000 # 训练过程会迭代多少次(?训练)
  eval_freq: 200 #200 # 每 eval_freq轮迭代，触发一次评估，评估后输出奖励。
  # 待会输出的格式 [current_epoch/total_epochs]：表示“当前训练轮次 / 总轮次”
  # 开始前先会输出一个R，评估初始模型的性能（作为对比？）
  finetune_wm: False

wandb:
  project: 
  entity: 
  group: 

# environment settings from TDMPC2
obs: state
task: reacher-easy
seed: ${general.seed}
tasks: ???
multitask: True
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
horizon: 16

buffer:
  _target_: pwm.utils.buffer.Buffer
  buffer_size: ???
  batch_size: 512
  horizon: ${horizon}
  device: ${general.device}
